### ISSUE TITLE
feedback window behavior change

### ISSUE THREAD

**Issue by scijones** [SoarGroup/VisualSoar#41]
I have VisualSoar 4.6.20 and 4.6.22. I only just recently downloaded and built 4.6.22. I believe my 4.6.20 is what came with the 9.6.3 Soar release.

There is a behavior difference between the two versions where I prefer the old behavior.

The "Feedback" tile at the bottom of the window previously would clear all text and then only include the text of the most recent command.

The new behavior is to just continuously append the output from each new command. I guess I have no opinion on what should be default, but at least having a toggle option for which one happens would be nice. Is this a bug?

**Comment by garfieldnate** [comment]
I changed this because *very* important errors were always being hidden, "very important" meaning ones that would lead to total project loss if the user saved. The reporting system could use an overhaul, but I did add in a mechanism for creating a sort of scope, meaning we can specify in code when we want to accumulate messages and when we want to clear them.

If you could be more specific about which messages are accumulating, then we could take a look.

**Comment by scijones** [comment]
I get the desire for accumulation and logging. It's literally just me complaining about one part of my workflow where I'm used to looking for errors in the datamap and then going one by one to clear them out. The old workflow: When the feedback window no longer has any errors when I click to check the datamap, I'm done!

Even just a manual "clear" button for that window would help. (Am I just missing it?)

Otherwise, I just find the scrolling cumbersome ("oh, that's from the last time I ran the command, not the current time, scrolled too far. Dangit, where was I?").

**Comment by scijones** [comment]
I'm trying to be overt that this is not that important in the grand scheme of things.

**Comment by garfieldnate** [comment]
Was an issue with the new atomic feedback logic. Thanks for reporting!
